<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class BasicRequest extends FormRequest
{
    protected function failedValidation(Validator $validator)
    {
        if ($this->expectsJson()) {
            $newErrors = [];
            foreach ($validator->errors()->toArray() as $key => $value) {
                $newErrors[] = ['key' => $key, 'description' => $value[0]];
            }
            $response = response()->json([
                'code' => 422,
                'error' => [
                    'message' => 'Validator Errors',
                    'errors' => $newErrors,
                    'errorLocalCode' => 'ERR22'
                ],
                'data' => null
            ], 422);
            throw new HttpResponseException($response);
        }
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
